### ISSUE TITLE
SessionStorage is ignored when used in localoptions object.

### ISSUE THREAD

**Issue by gurgelff** [digitalfortress-tech/localstorage-slim#30]
### What happened?

If one sets the storage option as sessionStorage in localoptions object it will be ignored and localStorage will be used instead.

Example:
```js
ls.set("testItem", "123", {storage: sessionStorage});
```

It will save ```testItem``` in localStorage and not in sessionStorage. It can be observed on browser dev tools.

Also, when retrieving data, the library also ignores the storage option:
```js
ls.get("testItem", {storage: sessionStorage});
```

It will retrieve the object not only in sessionStorage but also in localStorage. Not sure if the last behavior is intended though.

I provided a codepen project that shows both local and session behavior.

### Affected version

v2.7.0

### Reproduction URL

https://codepen.io/gurgelff/pen/OJdoyxr

### How to reproduce?

1 - Go to the provided codepen link
2 - Write some value in input field, like 123 (the code is already set to use sessionStorage in localconfig object).
3 - Notice that "_Get from sessionStorage (native API):_" returns nothing from SessionStorage.
4 - Notice also that both session and local storage using the library return some values, even though the saved value is only present in session, and not in localStorage.

### Browsers

Firefox, Brave

### Additional context

On Codepen, when using global config the issue seems resolved. But a localconfig scope is something useful that needs to be solved.

There is also an issue when used in Angular, that even with a global config it still doesn't use sessionStorage, but that is a matter for another issue.

**Comment by Droppix** [comment]
same...

**Comment by niketpathak** [comment]
Hello,
currently, switching between 2 different storage types on the fly within the same instance is not supported.
The typing info should have been more specific along with some documentation. Thanks to you, this typing info will be added in the next release. 
However, currently, you can use either localStorage or sessionStorage but **not both on the same instance**.
So what you did in your JS fiddle (_`ls.set('x', {storage: sessionStorage});`_ ) has no effect because the storage option is completely ignored while using the `get()` or `set()` API. you can only define the storage globally. 

If you need to use both sessionStorage and localStorage together with this library, you will have to duplicate your imports, for example

```js
import ls from 'localstorage-slim';
import ss from 'localstorage-slim';


ss.config.storage = sessionStorage;  // configure sessionStorage globally
// ls.config.storage = localStorage; (this is not required since the library defaults to using localStorage)

ss.set('item 1', 'value 1'); // stored in sessionStorage
ls.set('item A', 'value A'); // stored in localStorage
```

If you are using a CDN, then the library is exposed at `window.ls`. 
so to use sessionStorage **_alone_**, you can update the global config, 
`window.ls.config.storage = sessionStorage;` 

However, if you wish to use the same library for both local + session storage via CDN, you can achieve that by doing

```js
// duplicate the library (i.e create 2 different instances of the same library)
window.ss = {
 ...window.ls
} ;

window.ss.config.storage = sessionStorage; // configure sessionStorage globally
// window.ls.config.storage = localStorage; // this line is not needed as it defaults to using localStorage

window.ss.set('item 1', 'value 1'); // stored in sessionStorage
window.ls.set('item A', 'value A'); // stored in localStorage
```

Hope that helps.
